name: Deploy para Produção

on:
  push:
    branches:
      - main  # Executa o deploy sempre que a main for atualizada

jobs:
  deploy:
    runs-on: self-hosted  # Diz para rodar no seu servidor de produção
    
    steps:
      - name: Baixar o código do GitHub
        uses: actions/checkout@v4  # Baixa os arquivos do repositório na pasta do runner

      - name: Atualizar arquivos de produção
        run: |
          # Digite aqui os comandos para mover os arquivos ou reiniciar seu app
          # Exemplo: cp -r * /var/www/html/ echo "Arquivos baixados com sucesso no servidor!"
          robocopy . "C:\Apache64\htdocs\blinda" /E /Z /R:5 /W:5
          if ($lastexitcode -le 8) { exit 0 } else { exit $lastexitcode }
          Write-Output "Deploy concluído com sucesso!"
